### ISSUE TITLE
Screenshot or it didn't happen

### ISSUE THREAD

**Issue by heymatthew** [Pluies/Seitunes#1]
Looks cool, you should chuck something into your readme to show it off ;-).

**Comment by Pluies** [comment]
![seitunes-1-play](https://cloud.githubusercontent.com/assets/344835/6964138/e7404ad0-d9a2-11e4-8b4a-dde913967eac.png)
![seitunes-2-help-paused](https://cloud.githubusercontent.com/assets/344835/6964139/e748ca02-d9a2-11e4-85c0-d1a7bd7b03a9.png)
![seitunes-3-help-playing](https://cloud.githubusercontent.com/assets/344835/6964140/e74c92d6-d9a2-11e4-8b14-d85089a75328.png)

**Comment by Pluies** [comment]
@theflimflam Done!

**Comment by heymatthew** [comment]
Chur ;)
